# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'jalkametri' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jalkametri

  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

end
